# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.cache/wt [current_project]
set_property parent.project_path /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.srcs/sources_1/ip/data_mem/data_mem.xci
set_property is_locked true [get_files /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.srcs/sources_1/ip/data_mem/data_mem.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top data_mem -part xc7a100tcsg324-1 -mode out_of_context
rename_ref -prefix_all data_mem_
write_checkpoint -noxdef data_mem.dcp
catch { report_utilization -file data_mem_utilization_synth.rpt -pb data_mem_utilization_synth.pb }
if { [catch {
  file copy -force /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.runs/data_mem_synth_1/data_mem.dcp /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.srcs/sources_1/ip/data_mem/data_mem.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.srcs/sources_1/ip/data_mem/data_mem_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.srcs/sources_1/ip/data_mem/data_mem_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.srcs/sources_1/ip/data_mem/data_mem_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.srcs/sources_1/ip/data_mem/data_mem_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.ip_user_files/ip/data_mem]} {
  catch { 
    file copy -force /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.srcs/sources_1/ip/data_mem/data_mem_stub.v /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.ip_user_files/ip/data_mem
  }
}

if {[file isdir /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.ip_user_files/ip/data_mem]} {
  catch { 
    file copy -force /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.srcs/sources_1/ip/data_mem/data_mem_stub.vhdl /home/matthijsbos/Dropbox/fpgaedu/mips-fpgaedu/mips-fpgaedu.ip_user_files/ip/data_mem
  }
}
